# Generated by Django 5.1.4 on 2025-01-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد کلاس')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد درس')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('practical_units', models.PositiveIntegerField(default=0, verbose_name='تعداد واحد عملی')),
                ('theoretical_units', models.PositiveIntegerField(default=0, verbose_name='تعداد واحد نظری')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='محل دفتر')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='گروه آموزشی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.CharField(blank=True, max_length=200)),
                ('exam_time', models.CharField(blank=True, max_length=100)),
                ('max_capacity', models.IntegerField()),
                ('registered_students', models.CharField(max_length=2)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('delivery_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.professor')),
            ],
        ),
    ]
