# Generated by Django 5.1.4 on 2025-01-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_first_name_professor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='code',
        ),
    ]
