# Generated by Django 5.1.4 on 2025-01-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_professor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredcourse',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.professor', verbose_name='استاد'),
        ),
    ]
