# Generated by Django 5.1.4 on 2025-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_offeredcourse_exam_date_offeredcourse_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredcourse',
            name='weekday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offeredcourse',
            name='weekday_end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offeredcourse',
            name='weekday_start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
